spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fitness_tracker_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: Pepi1234@
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages/messages
    encoding: UTF-8

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name: